<?php
return [
    [
        'id' => 1,
        'date' => '2021-06-17',
        'day' => '17',
        'month' => 'június',
        'title' => 'KECSKEMÉTI SZALON',
        'text' => '2021 június 17.én, a SPALETTA ÉTTEREM ÉS SÖRHÁZBAN indítottuk el a Nemzeti Együttműködési Alap támogatásával, a KECSKEMÉTI SZALON elnevezésű -10 rendezvényből álló projektünket. A sorozatot, Kalmár Ferenc nagykövet, miniszteri biztos nyitotta meg. Közreműködött Jármai Edit énekesnő. Az estünk egyben tárlat megnyitó is volt. Két hétig Kovács Emil Lajos erdélyi festőművész alkotásait mutattuk be',
        'hero_image' => 3,
        'images' => 5,
    ],
    [
        'id' => 2,
        'date' => '2021-07-01',
        'day' => '01',
        'month' => 'július',
        'title' => 'KECSKEMÉTI SZALON 2',
        'text' => 'Pillanat képek" a KECSKEMÉTI SZALON július 1.-i rendezvényéről.
Almási Zsuzsa és Bíró Ernő akvarell-festők tárlatát, Szappanos István festőművész nyitotta meg. Vendégünk ENDREI JUDIT volt. Közreműködött: Palásti Máté, gitárművész.',
        'hero_image' => 1,
        'images' => 6,
    ],
    [
        'id' => 3,
        'date' => '2021-07-15',
        'day' => '15',
        'month' => 'július',
        'title' => 'KECSKEMÉTI SZALON 3',
        'text' => 'A KECSKEMÉTI SZALON estjén, HARSÁNYI ZSUZSANNA ÉS TANÍTVÁNYAI alkotásait mutattuk be. Közreműködött. GÖDÉNY ANIKÓ énekesnő!',
        'hero_image' => 1,
        'images' => 4,
    ],
    [
        'id' => 7,
        'date' => '2021-07-29',
        'day' => '29',
        'month' => 'július',
        'title' => 'KECSKEMÉTI SZALON 4',
        'text' => '2021 július 29-én, Gyenes Kata fotográfus és Dunszt István festőművész mutatkozott be.
A tárlatot KOVÁCS ÁGNES művészettörténész nyitotta meg.
Közreműködött: NAGY NIKOLETT  táncművész',
        'hero_image' => 1,
        'images' => 5,
    ],
    [
        'id' => 4,
        'date' => '2021-08-12',
        'day' => '12',
        'month' => 'augusztus',
        'title' => 'KECSKEMÉTI SZALON 5',
        'text' => '2021 augusztus 12-én, a KECSKEMÉTI SZALON programjaként MÁRTONFI BENKE MÁRTA festőművész mutatkozott be. Tárlatát Székelyné Kőrösi Ilona történész,  etnográfus nyitotta meg.
Közreműködtek: Kökény Eszter és Bránya Eszter hegedűművészek.',
        'hero_image' => 1,
        'images' => 5,
    ],
    [
        'id' => 5,
        'date' => '2021-08-26',
        'day' => '26',
        'month' => 'augusztus',
        'title' => 'KECSKEMÉTI SZALON 6',
        'text' => '2021. augusztus 26.án, a KECSKEMÉTI SZALON estjén a SPALETTA ÉTTEREM ÉS SÖRHÁZBAN,  GÖRE ÁGNES és SKULTÉTI ÁRPÁD festményeit mutattuk be: Megnyitót mondott: SZAPPANOS ISTVÁN festőművész. Közreműködött: CANDYMEN DUO
Vendégünk volt: BUDAY PÉTER mesterszakács, média személyiség.',
        'hero_image' => 1,
        'images' => 5,
    ],
    [
        'id' => 6,
        'date' => '2021-09-09',
        'day' => '09',
        'month' => 'szeptember',
        'title' => 'KECSKEMÉTI SZALON 7',
        'text' => '2021 szeptember 9-én, Bóna Edit festményeit és Farkas Gábor grafikáit mutattuk be. A  KCSKEMÉTI SZALON rendhagyó estjén az ismert házaspárt, Kovács Ágnes művészettörténész faggatta a képzőművészethez kötődő kapcsolataikról. A tárlaton túl a szórakoztatásról Farkas Gábor zenész társaival együtt gonoskodott. A vendéglátást, mint minden alkalommal a SPALETTA ÉTTEREM ÉS SÖRHÁZ biztosította!',
        'hero_image' => 1,
        'images' => 5,
    ],
    [
        'id' => 8,
        'date' => '2021-09-23',
        'day' => '23',
        'month' => 'szeptember',
        'title' => 'KECSKEMÉTI SZALON 8',
        'text' => '2021 szeptember 23.-án, A KECSKEMÉTI SZALON programjaként BELLA RÓZSA  grafikusművész és Ziegler Németh Ferenc festőművész kamaratárlatát, Kovács Ágnes művészettörténész nyitotta meg. Vendégünk volt: KOCSIS NOÉMI író-újságíró volt. Közreműködött: Gödény Anikó énekesnő!',
        'hero_image' => 1,
        'images' => 5,
    ],
    [
        'id' => 9,
        'date' => '2021-10-07',
        'day' => '07',
        'month' => 'október',
        'title' => 'KECSKEMÉTI SZALON 9',
        'text' => 'A KECSKEMÉTI SZALON ESTJÉN 202 október 7.-én, BALOGH JÓZSEF ZSOLT és DOBOS EDIT képzőművészek alkotásait mutattuk be.
A tárlatot KOVÁCS ÁGNES művészettörténész nyitotta meg.
VENDÉGÜNK volt CSATOS ERIKA az Álomjövő Tanácsadó Iroda alapító-tulajdonosa volt.
Közreműködött:DIAN RÓBERT gitárművész',
        'hero_image' => 1,
        'images' => 5,
    ],
    [
        'id' => 11,
        'date' => '2021-10-11',
        'day' => '11',
        'month' => 'október',
        'title' => 'Képzőművészeti kincseink',
        'text' => 'A Nemzeti Együttműködési Alap és Kecskemét Megyei Jogú Város támogatásával rendeztük meg a 2021-es programsorozatunk zárásaként a "KÉPZŐMŰVÉSZETI KINCSEINK" című kiállításunkat az Ifjúsági Otthon Tükörtermében. A tárlaton 21 egykori jeles városunkhoz kötődő képzőművész alkotásait mutattuk be. Az emlékező tárlatra katalógust is készítettünk.A kiállítás anyagát az örökösöktől szereztük be. Köszönet érte!
A megnyitón a vendégeket SZEMEREYNÉ PATAKI KLAUDIA polgármester asszony köszöntötte. A tárlatot dr.FELEDY BALÁZS művészetkritikus, művészeti író nyitotta meg.Közreműködött: DAIN RÓBERT gitárművész.',
        'hero_image' => 1,
        'images' => 5,
    ],
    [
        'id' => 10,
        'date' => '2021-10-21',
        'day' => '21',
        'month' => 'október',
        'title' => 'KECSKEMÉTI SZALON 10',
        'text' => 'A KECSKEMÉTI SZALON programsorozatunk zárásaként CSURGÓ ERIKA grafikus és ANGELO MINUTI szobrászművész alkotásai mutattuk be, 2021 október 21.én. 
Vendégünk volt: DOLHAI ATTILA  Jászai Mari-díjas színművész. Az esten olasz dallamok csendültek fel, a közönség nagy örömére! A  sikeres eseménysorozatot KALMÁR FERENC rendkívüli és meghatalmazott nagykövet, miniszteri biztos méltatta.',
        'hero_image' => 1,
        'images' => 5,
    ],
    [
        'id' => 12,
        'date' => '2022-02-26',
        'day' => '26',
        'month' => 'február',
        'title' => 'MAGYAR KULTÚRA MAGAZIN lapbemutató',
        'text' => 'MAGYAR KULTÚRA MAGAZIN lapbemutatója a Spalettában, az Itt vagyunk, támogatunk egyesület a Petőfi Kulturális Ügynökséggel együttműködve...',
        'hero_image' => 2,
        'images' => 6,
    ],
    [
        'id' => 13,
        'date' => '2022-04-21',
        'day' => '21',
        'month' => 'április',
        'title' => 'KECSKEMÉTI SZALON 2 programsorozat',
        'text' => '2022.04.21-én, a A Nemzeti Együttműködési Alap támogatásával, elindítottuk  a KECSKEMÉTI SZALON 2 programsorozatunkat a SPALETTÁBAN...  Nyitó eseményünk vendége: BAHGET ISKANDER, Kossuth díjas fotóművész volt.  A kéthetente csütörtökön 17 órakor jelentkező, 10 alkalomból álló eseménysorozatot Prof.Dr. Sztachó- Pekáry István önkormányzati képviselő, az Örökségvédelmi Bizottság elnöke köszöntötte.  Megnyitotta: Dr. Farkas Gábor Ybl díjas építész Közreműködött: Dian Róbert gitárművész.',
        'hero_image' => 1,
        'images' => 4,
    ],
    [
        'id' => 14,
        'date' => '2022-05-12',
        'day' => '12',
        'month' => 'május',
        'title' => 'KOVÁCS LÁSZLÓ "fotók a nagyvilágból" című tárlat',
        'text' => '2022 május 12-én, 17 órakor nyílt meg a Spaletta Étterem és Sörházban, KOVÁCS LÁSZLÓ "fotók a nagyvilágból" című tárlata.  Az alkotót Dr. Csőszi Tibor mutatta be Közreműködött: Gödény Anikó énekesnő.',
        'hero_image' => 2,
        'images' => 5,
    ],
];
